language: node_js

node_js:
- '15'
- '14'
- '12'
- '10'

install:
  - npm install

script:
  - npm test
  - sonar-scanner

addons:
  sonarcloud:
    organization: "beeblebrox3-github"
    token:
      secure: "IKglVF7YQRtKDa9SbjxCXuwlvEwM/T/1fDCZpgrFSZGxKj9EPIyfsHcYdyhhetYc3ePoMb+R7P57tELmZnwZy89LVCyDaTNjeAXW6Jmmkh+VrNgm82wLU8ujBx9frsBrH58Cdg2V2gC/J20FMJxOe1NDUAs4x7Yu3ctbFZw2QoXLFye12Um5/56cW/Eq4cUZ3wjlgqMQXaJQ/OHCnNmVQlxRdvcnxPdYka1wge4EVZlFxdqhBSnnQf4yruUyQAuH8Iy39voCG4bV09u4jtZ9OoXKIuRdM10HVw8Sn2DitZRXubTqF9EZo6XnuMY2zWWVJjhXP2JAbNujWGik1wZ5jNqL9bjf6RVsr4ZEMxFd0Fc+VUENrCrDLRAIXACLzl3ZJzdyyrBbVgjtOKYA0/Zz8S4fkvkIkDDRq4Psl+qyNsvV/Fc3Z/1LkHkmRtlQgxRmVonnFrapd2Kg/TGaWI7Za9jZZfq90xGiGHr0nY7LGoNeb9yxxYBezLOg2aMFBRSIxiXefpmDXCVn7ON8UPDDW+VEoqTUbk4IHsNADN2Rf9Ho9RkHr/sv6ZqPi+fahk4aHDxAIdgf0f+HG6u8QiGiIfTZio0uPeW/nk4VbcpYBa1GBb1dImk8KjoShPpvEk3WlZ6tKCmYXgeA2KqhHrDa/UYVBUcFDSzPI2IQJ1fWO+c="
