language: node_js

node_js:
- '11'
- '10'
- '8'

install:
  - yarn

script:
  - yarn test
  - sonar-scanner

addons:
  sonarcloud:
    organization: "beeblebrox3-github"
    token:
      secure: $SONAR_TOKEN
